# Generated by Django 5.1.3 on 2024-12-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0003_productsfulldesc_shortprod_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsfulldesc',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='productsfulldesc',
            name='color',
        ),
    ]
