# Generated by Django 5.1.3 on 2024-12-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_blogs_singleblogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='productsfulldesc',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='shortprod',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='image1',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='image2',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='image3',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='image4',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='image5',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
