# Generated by Django 5.1.3 on 2024-12-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0007_alter_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleblogs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/blog/'),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/blog/'),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/blog/'),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/blog/'),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/blog/'),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/blog/'),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='part1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singleblogs',
            name='part2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
