# Generated by Django 5.1.3 on 2024-12-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0008_alter_singleblogs_image_alter_singleblogs_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsfulldesc',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsfulldesc',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shortprod',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shortprod',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productsfulldesc',
            name='image',
            field=models.ImageField(upload_to='static/img/product/'),
        ),
        migrations.AlterField(
            model_name='shortprod',
            name='image',
            field=models.ImageField(upload_to='static/img/product/'),
        ),
    ]
